### PR TITLE
Ninja build modifications

### PR DESCRIPTION
**Pull request by ghost**
Note: clang still needs modifications.

### CODE REVIEW

**Comment by isuruf** [comment]
Does this work? I thought `flang -E` doesn't work and ninja needs the preprocessed output

**Comment by ghost** [comment]
Note that there are two modifications to `clang` that are required:

1. Replacing the `-E` argument with `-Mpreprocess`, I'm thinking here:

https://github.com/flang-compiler/clang/blob/94872eab7578af538341f30f2a85f3dc9952dda7/tools/driver/cc1_main.cpp#L170

2. Only invoking the `flang1` executable.

**Comment by ghost** [comment]
@isuruf Yes, this works:

```
> flang1 -es -preprocess test.f
```

**Comment by ghost** [comment]
The other option is looking at CMake internals to replace `flang -E` with `flang1 -preprocess -es`.

**Comment by isuruf** [comment]
CMake support can be added if `flang -preprocess -es` worked, but it seems you need `flang1`

**Comment by ghost** [comment]
Yes, the driver (clang) support is also broken. This is half of the fix. It's probably better to fix the driver, but rebuilding clang is painful.

**Comment by ghost** [comment]
Let me hack together a patch for clang.

**Comment by isuruf** [comment]
Thanks. This can be a separate PR for upstream. Any progress on CLA?

**Comment by ghost** [comment]
You know as much as I do.

**Comment by ghost** [comment]
@isuruf This works with the two patches:

```
flang -v -Mpreprocess ps13.f | Out-File ps13.f.pp
```

**Comment by ghost** [comment]
I think I can get to `flang -E` with a few more iterations...

**Comment by ghost** [comment]
Tested; merging.

**Pull request merged**
