### PR TITLE
Test in appveyor

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
```
[00:11:32]   Expected Passes    : 582
[00:11:32]   Unexpected Failures: 388
```

**Comment by isuruf** [comment]
Missing symbols from the fortran modules (ieee_arithmetic, ieee_exceptions, etc) are responsible for most of the test failures.

**Comment by ghost** [comment]
Yes, I think the runtime libraries are not linked.

**Comment by ghost** [comment]
I want to see the linker command.

**Comment by xoviat** [comment]
@isuruf Do you have the static OpenBLAS lib build with flang?

**Comment by isuruf** [comment]
I have a shared build going with flang + ASM (Haswell). I think this will take another half an hour to an hour.
I also have a static build of netlib's lapack + blas

**Comment by xoviat** [comment]
Do you have the static build now? Will use to run the scipy tests.

**Comment by isuruf** [comment]
https://github.com/isuruf/lapack/releases/tag/flang-build

**Comment by xoviat** [comment]
@isuruf Your libs are bad; they don't include the runtime libraries. You can just re-run lib.exe as such to fix that:

```
lib.exe flang.lib flangrti.lib lapack.lib /OUT:lapack_fixed.lib
```

**Comment by isuruf** [comment]
Updated

**Comment by xoviat** [comment]
Unfortunately I received an SEH fault when running the scipy tests. I suspect it's related to  the debug DLL. I think we should drop the signal handler for now.

**Comment by isuruf** [comment]
Lots of tests failing because of https://github.com/flang-compiler/flang/issues/320

**Pull request closed without merging**
