### PR TITLE
Align to cache line set to 32 for windows

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/isuruf/flang/issues/34

### CODE REVIEW

**Comment by ghost** [comment]
Looks like my other attempt was a failure. Does this compile the lapack tests?

**Comment by isuruf** [comment]
Yes, it's compiling now. (Btw, I had to do ugly hacks to support flang in CMake.)

**Comment by isuruf** [comment]
BLAS tests pass successfully. LAPACK tests fail saying `xlaenv_` symbol is missing

**Comment by ghost** [comment]
Try tossing this in there: http://www.netlib.org/lapack/explore-html/d4/dfa/_e_i_g_2xlaenv_8f_source.html

**Comment by isuruf** [comment]
I had accidentally removed a line in CMakeLists.txt when working on it. That's why the symbol is missing.

**Comment by isuruf** [comment]
I've uploaded the newest build to anaconda.org.
All tests in BLAS and LAPACK pass.

**Pull request merged**
