### PR TITLE
[appveyor] try to build tests

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@isuruf Do you have any idea how to run the tests?

**Comment by isuruf** [comment]
Nope. @albertziegenhagel might

**Comment by ghost** [comment]
@isuruf Something may be wrong with appveyor.

**Comment by isuruf** [comment]
What's the issue?

**Comment by ghost** [comment]
Nothing. It works fine.

**Comment by ghost** [comment]
I think it will work if we run nmake inside of MSYS2?

**Comment by ghost** [comment]
Not sure what the best way forward is, as I don't understand lit very well.

**Comment by ghost** [comment]
Actually the problem is fixable if we fork lit. I think that's the best option.

**Comment by ghost** [comment]
@isuruf So I'm not going to be able to iterate if we build flang every time before testing. We'll need to cache the build so that we can have quick feedback on whether the lit changes work.

**Comment by isuruf** [comment]
How do we do that? `clcache`?

**Comment by ghost** [comment]
Can't we just cache the `build` directory? One problem is that appveyor restricts the cache much more than travis. But wait on the cache until I finish more cleanups.

**Comment by ghost** [comment]
@ddunbar how can we get fixes into lit? Where is the repository?

**Comment by ddunbar** [comment]
The lit code is still part of LLVM, in utils/lit

**Comment by isuruf** [comment]
@xoviat, now the tests are running. I'm hitting a strange issue now. lit tests are now run. A test is like this,
```
# RUN: KEEP_FILES=%keep FLAGS=%flags TEST_SRC=%s MAKE_FILE_DIR=%S/.. bash %S/runmake | tee %t 
# RUN: cat %t | FileCheck %S/runmake
```
In the first command output of the bash command is redirected to a temp file `%t`.
Issue is that when the `tee` command is given the output is different.
compare
```
UOFI+idf2@DESKTOP-SQ1JTKT  /c/Users/idf2/flang/build2/test/f90_correct/lit
$ KEEP_FILES= FLAGS="" TEST_SRC=C:/Users/idf2/flang/test/f90_correct/lit/ab20.sh MAKE_FILE_DIR=C:/Users/idf2/flang/test
/f90_correct/lit/.. bash C:/Users/idf2/flang/test/f90_correct/lit/runmake
mkdir: cannot create directory 'ab20': File exists
123
rm -f ab20.out core *.d *.mod FOR*.DAT FTN* ftn* fort.*
------------------------------------ building test build
clang -c  C:/Users/idf2/flang/test/f90_correct/lit/../src/check.c -o check.o
flang -c -IC:/Users/idf2/flang/test/f90_correct/lit/../src      C:/Users/idf2/flang/test/f90_correct/lit/../src/ab20.f -o ab20.o
warning: overriding the module target triple with x86_64-pc-windows-msvc19.0.24215 [-Woverride-module]
1 warning generated.
flang -IC:/Users/idf2/flang/test/f90_correct/lit/../src      ab20.o check.o  -o ab20.out
libcmt.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
------------------------------------ executing test ab20
ab20.out
  1 tests completed. 1 tests PASSED. 0 tests failed.
make: 'verify' is up to date.
```
vs 
```
UOFI+idf2@DESKTOP-SQ1JTKT  /c/Users/idf2/flang/build2/test/f90_correct/lit
$ KEEP_FILES= FLAGS="" TEST_SRC=C:/Users/idf2/flang/test/f90_correct/lit/ab20.sh MAKE_FILE_DIR=C:/Users/idf2/flang/test
/f90_correct/lit/.. bash C:/Users/idf2/flang/test/f90_correct/lit/runmake | tee C:/Users/idf2/flang/build2/test/f90_cor
rect/lit/Output/ab20.sh.tmp
mkdir: cannot create directory 'ab20': File exists
123
rm -f ab20.out core *.d *.mod FOR*.DAT FTN* ftn* fort.*
------------------------------------ building test build
clang -c  C:/Users/idf2/flang/test/f90_correct/lit/../src/check.c -o check.o
flang -c -IC:/Users/idf2/flang/test/f90_correct/lit/../src      C:/Users/idf2/flang/test/f90_correct/lit/../src/ab20.f -o ab20.o
warning: overriding the module target triple with x86_64-pc-windows-msvc19.0.24215 [-Woverride-module]
1 warning generated.
flang -IC:/Users/idf2/flang/test/f90_correct/lit/../src      ab20.o check.o  -o ab20.out
libcmt.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
------------------------------------ executing test ab20
ab20.out
make: 'verify' is up to date.
```

Note that `1 tests completed. 1 tests PASSED. 0 tests failed.` is missing in the second. Any ideas why?

**Comment by ghost** [comment]
Do we know where `FileCheck` is located? Maybe that's parsing the output and failing the test.

**Comment by isuruf** [comment]
FileCheck is not used. It's the first command that's the issue. `KEEP_FILES=%keep FLAGS=%flags TEST_SRC=%s MAKE_FILE_DIR=%S/.. bash %S/runmake | tee %t `

**Comment by ghost** [comment]
Could be that `tee` doesn't exist. It's a bash command but is this run inside bash? And even if it is, Python may not be picking it up.

**Comment by ghost** [comment]
It would need to be an executable rather than just a bash function, *and* Python would need to be run inside MSYS2 for that to theoretically work.

**Comment by isuruf** [comment]
This is run inside a msys2 bash shell and the outputs above are when I run the commands manually without lit.

>  Python may not be picking it up.

what do you mean?

**Comment by ghost** [comment]
Where's `tee.exe`?

**Comment by isuruf** [comment]
`C:\msys64\bin\usr\bin`

**Pull request closed without merging**
