### PR TITLE
Remove adding -DLINUX

### PR DESCRIPTION
**Pull request by isuruf**
cc @xoviat

### CODE REVIEW

**Comment by isuruf** [comment]
Looks like @diorcety's fork has this change as well. We should have a look at that repo and cherry-pick relevant changes.

**Comment by ghost** [comment]
@pv How do you cancel the older PR builds on scipy? I cannot figure that option out.

**Comment by isuruf** [comment]
https://github.com/JuliaLang/julia/blob/master/appveyor.yml#L40-L44

**Comment by ghost** [comment]
That's not what I'm talking about, look here:

https://ci.appveyor.com/project/scipy/scipy/build/1.0.1004

**Comment by ghost** [comment]
Also here: https://ci.appveyor.com/project/bunnei/citra/build/1.0.6240

**Comment by ghost** [comment]
They have the "More recent PR #8075 build has been stated."

**Comment by ghost** [comment]
BTW it's called rolling builds.

**Pull request merged**
