### PR TITLE
[cmake] set target arch and OS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by isuruf** [comment]
Shall I fix this and force push?

**Comment by ghost** [comment]
One issue that came up is that there was one build where `CMAKE_SIZEOF_VOIDP` was not correct; `WIN64` was not defined. IMO that change should stay.

**Comment by isuruf** [comment]
Okay, I'll fix that

**Comment by ghost** [comment]
Thanks. Then maybe we can figure out why I couldn't rebuild flang on conda-forge.

**Comment by isuruf** [comment]
I'll be back in an hour and fix this

**Comment by ghost** [comment]
Thanks.

**Comment by isuruf** [comment]
Done

**Pull request closed without merging**
