### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by isuruf** [comment]
https://superuser.com/a/352499 seems to suggest that the fortran program is doing something wrong when the output is redirected.

**Comment by ghost** [comment]
Okay. I guess we should publish a conda package of our new compiler? How does that work?

**Comment by isuruf** [comment]
you mean https://github.com/flang-compiler/clang or https://github.com/flang-compiler/flang ?

**Comment by isuruf** [comment]
Maybe there is something wrong with `isatty3f` function

**Comment by ghost** [comment]
Could be. WRT conda package I think it would need all of the libraries and executables from both projects.

**Comment by ghost** [comment]
Idea is to get this into numpy and see what it can compile. Need to be able to use on appveyor.

**Comment by isuruf** [comment]
Okay, I'll make a conda package and publish it to anaconda.org.

**Pull request merged**
