### PR TITLE
CMake: Fix warnings

### PR DESCRIPTION
**Pull request by ghost**
This PR relies on Ninja's builtin module detection, which failed before because the module directory was previously the same.

Closes gh-114.

### CODE REVIEW

**Comment by isuruf** [comment]
@xoviat, sorry, I just did a rebase of the commits. I'll fix this

**Comment by ghost** [comment]
Not a problem. Don't touch it for now because I want to see the results of the Travis build.

**Comment by ghost** [comment]
@isuruf Is there any reason why this fix would not work? It's significantly simpler than the other fix.

**Review by isuruf — DISMISSED** [review]
+1. Can you move the sources `iso_c_bid.F95` etc to back  to where it was to reduce the diff?

**Comment by ghost** [comment]
Note: issue filed at https://gitlab.kitware.com/cmake/cmake/issues/17606

**Comment by isuruf** [comment]
Works for me locally on linux

**Pull request merged**
