### PR TITLE
Windows linker issues

### PR DESCRIPTION
**Pull request by albertziegenhagel**
This merge request should resolve all  remaining problems when linking and make your appveyor run working.

I still do not fully understand how it could work on your own machine without those changes (even with the  CMake changes from https://gitlab.kitware.com/cmake/cmake/merge_requests/1404)

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks. I set CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=yes on the command line (forgot to do that on appveyor), but this is better.

> I still do not fully understand how it could work on your own machine without those changes (even with the CMake changes from https://gitlab.kitware.com/cmake/cmake/merge_requests/1404)

Me neither. I'll check again with the conda package that I'm using on appveyor.

**Comment by isuruf** [comment]
Building on appveyor pass. Thanks

**Comment by albertziegenhagel** [comment]
Maybe you want to call 

```
nmake check-flang
```

in the appveyor file as well. This should try to run some test on the resulting binaries. I am currently not able to test this on my own machine, since I have to rebuild llvm and clang-flang first.

**Comment by isuruf** [comment]
Sure.

> I am currently not able to test this on my own machine, since I have to rebuild llvm and clang-flang first.

You can use the conda packages in my channel if you don't mind binaries.

**Pull request merged**
